frontend:
  url: https://humrates.ew.r.appspot.com

#Mailing properties
mail:
  debug: true
  transport:
    protocol: smtp
  smtp:
    auth: true
    starttls.enable: true
    host: smtp.gmail.com
    port: 587
  sender:
    email: loic.madies@gmail.com
    password: wcomtrejcqtltnuy

# Database
db.driver: org.postgresql.Driver
db.url: jdbc:postgresql:///authentificator?cloudSqlInstance=humrates:europe-west1:global-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory
db.username: authentificator
db.password: authentificator

spring: 
  profiles:
    active: postgresql
  cloud:
    gcp.sql.database-name: authentificator
    gcp.sql.instance-connection-name: humrates:europe-west1:global-db
  datasource:
    username: authentificator
    password: authentificator
    hikari.maximum-pool-size: 10

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  hbm2ddl.auto: update
entitymanager.packagesToScan: com.lma.authentificator

# Security
jwt:
  expiration.delay: 172800
  unchecked.uri.list: /account/confirmRegister,/account/register,/account/login
